### ISSUE TITLE
Change the router logic to controller files.

### ISSUE THREAD

**Issue by Souvikns** [Ninja-Developers/Quizzer#10]
Currently, the router logic is in the router files, it is sure to get massive, and thus shifting the code to its separate controller files will help maintaining the codebase.

**Comment by rohitjethoe** [comment]
So you just want the routes to the controller file?

**Comment by Souvikns** [comment]
The router logic in the router files, just shift them to individual controller files, so that the codebase is clean

**Comment by imabp** [comment]
@rohitjethoe we are happy to see you interested for this issue. I have few details for you to help you out.

### Issue Objective: Modularity and Readiblity.
### Description: It is required, in order to have effective routing.
#### Example.
_Here is one  example._
### Before Modularity
In routes/route.js
```
 router.route.post( /*LOGIC*/ )
                    .get(/*LOGIC*/)
```
### After achieving modularity:
**In controller/route.js**
```
const getroute=(params)=>{
/*LOGIC*/
}
const postroute=(params)=>{
/*LOGIC*/
}
module.exports={
getroute,
postroute
}
```
**In routes/route.js**
```

import {getroute,postroute} from '../controller/route'
router.route.post( postroute() ).get(getroute())
module.exports=router;
```

**Comment by rohitjethoe** [comment]
Aah I get it. I'll will start working on this in an hour.

**Comment by imabp** [comment]
Nice work @rohitjethoe !! Well done.
