### ISSUE TITLE
Fix the contributers section in reademe 

### ISSUE THREAD

**Issue by Souvikns** [Ninja-Developers/Quizzer#34]
We are using this [bot](https://allcontributors.org/), to update a reademe for new contributors, currently it is having a problem and not showing two users. also a good way of automation could be done where the contributor automatically gets added when he makes a first pr.

**Comment by lee00286** [comment]
Hello, may I contribute to this issue? I would like to update the readme. Also, for automation, I want to suggest [all-contributors-cli](all-contributors-cli), which seems to be automatically adding the contributor.

**Comment by Souvikns** [comment]
@lee00286 I am assigning this to you.

**Comment by lee00286** [comment]
I couldn't find a way to add the contributor automatically, but the implementation of all-contributors-cli allows to add contributor through commands, without calling the bot. This way allows contributors to add themselves on their own, but I'm not sure if this is an enough solution for this issue...

**Comment by Souvikns** [comment]
ok I searched the all-contributors-cli, it is a npm package and we are using all-contributors bot currently. I guess this might solve our issue https://github.com/marketplace/actions/auto-add-contributors

**Comment by lee00286** [comment]
I created the yml file for the Action but I'm not sure if it is working since I never made any pull request. May I create the pull request to see how it works? If it doesn't work, then I would try [All Contributors Plugin](https://preview.npmjs.com/package/@auto-it/all-contributors) as well.

**Comment by Souvikns** [comment]
@lee00286 you can go ahead and create the pr

**Comment by Souvikns** [comment]
@lee00286 I have merged your pr, but I guess nothing happened will it start working from the next contributor that is being added

**Comment by lee00286** [comment]
@Souvikns I found some issues in the last commit file, and one of them says "Resource not accessible by integration." This error happens since I don't have the permission to the repository and running in the fork.

Can you please try running the Action after I create a new pull request and tell me if it is working or not? The Action will automatically run at 20:20 UTC as it is coded, but you can change it in .yml file.

**Comment by Souvikns** [comment]
Can you attach any documentation about the action? I have to see what permissions it needs.

**Comment by lee00286** [comment]
@Souvikns The Action will run as soon as you merge my PR and generate the contributors section in README.md, since I saw it is working with my personal repo... If the Action runs successfully, then I will delete the original contributors table and push it.

I think [this issue](https://github.com/actions/first-interaction/issues/10) and [this blog](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/) talks about the permission issue.

**Comment by lee00286** [comment]
I saw the commit in README.md and found out that `## Contributors` is deleted from the file. If this project is going to use Auto-Add Contributions Action, then the automation won't work if ✨ is after the `## Contributors`...
